### ISSUE TITLE
Might be helpful to have a sample_ID column

### ISSUE THREAD

**Issue by PennyWieser** [sarahshi/mineralML#4]
Might help to have a column in 
df_pred_nn that has a sample name or sample column you can allocate in the function, for easier stitching of MinML outputs with initial data later.

**Comment by sarahshi** [comment]
Commit [3ba10bd](https://github.com/sarahshi/mineralML/commit/3ba10bd04a7af458c95b7bfc714ffd0d628fac9d) should similarly address this.
